### ISSUE TITLE
build Failed

### ISSUE THREAD

**Issue by zwj-cheer** [youlaitech/vue3-element-admin#164]
运行build时会有报错
[Vue] Failed to create plugin TypeError: plugin is not a function                                                                                                                                                                  
    at /Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/@vue+language-core@2.1.6_typescript@5.5.4/node_modules/@vue/language-core/lib/plugins.js:55:30
    at Array.flatMap (<anonymous>)
    at createPlugins (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/@vue+language-core@2.1.6_typescript@5.5.4/node_modules/@vue/language-core/lib/plugins.js:52:10)
    at Object.createVueLanguagePlugin (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/@vue+language-core@2.1.6_typescript@5.5.4/node_modules/@vue/language-core/lib/languagePlugin.js:52:49)
    at /Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/vue-tsc@2.1.6_typescript@5.5.4/node_modules/vue-tsc/index.js:18:43
    at Object.apply (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/@volar+typescript@2.4.2/node_modules/@volar/typescript/lib/node/proxyCreateProgram.js:50:33)
    at getBuilderCreationParameters (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/typescript@5.5.4/node_modules/typescript/lib/tsc.js:123488:18)
    at createEmitAndSemanticDiagnosticsBuilderProgram (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/typescript@5.5.4/node_modules/typescript/lib/tsc.js:123982:81)
    at createIncrementalProgram (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/typescript@5.5.4/node_modules/typescript/lib/tsc.js:125787:10)
    at performIncrementalCompilation (/Users/zhaoweijie/Desktop/daotl/vue3-element-admin-thin/node_modules/.pnpm/typescript@5.5.4/node_modules/typescript/lib/tsc.js:125737:26)

**Comment by haoxianrui** [comment]
验证最新版本没问题，可以提供下node和pnpm版本
![image](https://github.com/user-attachments/assets/3e8d51eb-0b81-4350-9185-b252dbb89382)
